<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionstableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = array(
            0 =>
                array(
                    'id' => 1,
                    'name' => '后台管理',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/index',
                    'level' => 0,
                    'icon' => 'layui-icon-app',
                    'parent_id' => 0,
                    'display_menu' => 1,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            1 =>
                array(
                    'id' => 2,
                    'name' => '系统管理',
                    'guard_name' => 'admin',
                    'sort_order' => 10,
                    'url' => '/admin/system',
                    'level' => 0,
                    'icon' => 'layui-icon-set',
                    'parent_id' => 0,
                    'display_menu' => 1,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            2 =>
                array(
                    'id' => 3,
                    'name' => '控制台',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/index/main',
                    'level' => 1,
                    'icon' => 'layui-icon-home',
                    'parent_id' => 1,
                    'display_menu' => 1,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            3 =>
                array(
                    'id' => 4,
                    'name' => '角色管理',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/role',
                    'level' => 1,
                    'icon' => 'layui-icon-user',
                    'parent_id' => 2,
                    'display_menu' => 1,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            4 =>
                array(
                    'id' => 5,
                    'name' => '权限管理',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/permission',
                    'level' => 1,
                    'icon' => 'layui-icon-spread-left',
                    'parent_id' => 2,
                    'display_menu' => 1,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            5 =>
                array(
                    'id' => 6,
                    'name' => '用户管理',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/admin',
                    'level' => 1,
                    'icon' => 'layui-icon-friends',
                    'parent_id' => 2,
                    'display_menu' => 1,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            6 =>
                array(
                    'id' => 7,
                    'name' => '角色列表',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/role/index',
                    'level' => 2,
                    'icon' => '',
                    'parent_id' => 4,
                    'display_menu' => 1,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            7 =>
                array(
                    'id' => 8,
                    'name' => '查看角色',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/role/show',
                    'level' => 2,
                    'icon' => '',
                    'parent_id' => 4,
                    'display_menu' => 0,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            8 =>
                array(
                    'id' => 9,
                    'name' => '创建角色',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/role/create',
                    'level' => 2,
                    'icon' => '',
                    'parent_id' => 4,
                    'display_menu' => 0,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            9 =>
                array(
                    'id' => 10,
                    'name' => '保存角色',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/role/store',
                    'level' => 2,
                    'icon' => '',
                    'parent_id' => 4,
                    'display_menu' => 0,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            10 =>
                array(
                    'id' => 11,
                    'name' => '编辑角色',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/role/edit',
                    'level' => 2,
                    'icon' => '',
                    'parent_id' => 4,
                    'display_menu' => 0,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            11 =>
                array(
                    'id' => 12,
                    'name' => '修改角色',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/role/update',
                    'level' => 2,
                    'icon' => '',
                    'parent_id' => 4,
                    'display_menu' => 0,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            12 =>
                array(
                    'id' => 13,
                    'name' => '删除角色',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/role/destroy',
                    'level' => 2,
                    'icon' => '',
                    'parent_id' => 4,
                    'display_menu' => 0,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            13 =>
                array(
                    'id' => 14,
                    'name' => '权限列表',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/permission/index',
                    'level' => 2,
                    'icon' => '',
                    'parent_id' => 5,
                    'display_menu' => 1,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            14 =>
                array(
                    'id' => 15,
                    'name' => '查看权限',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/permission/show',
                    'level' => 2,
                    'icon' => '',
                    'parent_id' => 5,
                    'display_menu' => 0,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            15 =>
                array(
                    'id' => 16,
                    'name' => '创建权限',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/permission/create',
                    'level' => 2,
                    'icon' => '',
                    'parent_id' => 5,
                    'display_menu' => 0,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            16 =>
                array(
                    'id' => 17,
                    'name' => '保存权限',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/permission/store',
                    'level' => 2,
                    'icon' => '',
                    'parent_id' => 5,
                    'display_menu' => 0,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            17 =>
                array(
                    'id' => 18,
                    'name' => '编辑权限',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/permission/edit',
                    'level' => 2,
                    'icon' => '',
                    'parent_id' => 5,
                    'display_menu' => 0,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            18 =>
                array(
                    'id' => 19,
                    'name' => '修改权限',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/permission/update',
                    'level' => 2,
                    'icon' => '',
                    'parent_id' => 5,
                    'display_menu' => 0,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            19 =>
                array(
                    'id' => 20,
                    'name' => '删除权限',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/permission/destroy',
                    'level' => 2,
                    'icon' => '',
                    'parent_id' => 5,
                    'display_menu' => 0,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            20 =>
                array(
                    'id' => 21,
                    'name' => '管理员列表',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/admin/index',
                    'level' => 2,
                    'icon' => '',
                    'parent_id' => 6,
                    'display_menu' => 1,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            21 =>
                array(
                    'id' => 22,
                    'name' => '查看管理员',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/admin/show',
                    'level' => 3,
                    'icon' => '',
                    'parent_id' => 21,
                    'display_menu' => 0,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            22 =>
                array(
                    'id' => 23,
                    'name' => '创建管理员',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/admin/create',
                    'level' => 3,
                    'icon' => '',
                    'parent_id' => 21,
                    'display_menu' => 0,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            23 =>
                array(
                    'id' => 24,
                    'name' => '保存管理员',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/admin/store',
                    'level' => 3,
                    'icon' => '',
                    'parent_id' => 21,
                    'display_menu' => 0,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            24 =>
                array(
                    'id' => 25,
                    'name' => '编辑管理员',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/admin/edit',
                    'level' => 3,
                    'icon' => '',
                    'parent_id' => 21,
                    'display_menu' => 0,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            25 =>
                array(
                    'id' => 26,
                    'name' => '修改管理员',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/admin/update',
                    'level' => 3,
                    'icon' => '',
                    'parent_id' => 21,
                    'display_menu' => 0,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            26 =>
                array(
                    'id' => 27,
                    'name' => '删除管理员',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/admin/destroy',
                    'level' => 3,
                    'icon' => '',
                    'parent_id' => 21,
                    'display_menu' => 0,
                    'created_at' => '2019-05-22 13:56:01',
                ),
            27 =>
                array(
                    'id' => 35,
                    'name' => '网站设置',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/systemConfig/basal',
                    'level' => 1,
                    'icon' => 'layui-icon-set-sm',
                    'parent_id' => 2,
                    'display_menu' => 1,
                    'created_at' => '2019-06-23 04:58:48',
                ),
            28 =>
                array(
                    'id' => 36,
                    'name' => '内容管理',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/article',
                    'level' => 0,
                    'icon' => 'layui-icon-read',
                    'parent_id' => 0,
                    'display_menu' => 1,
                    'created_at' => '2019-06-25 14:35:19',
                ),
            29 =>
                array(
                    'id' => 37,
                    'name' => '文章列表',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/article/index',
                    'level' => 1,
                    'icon' => 'layui-icon-file-b',
                    'parent_id' => 36,
                    'display_menu' => 1,
                    'created_at' => '2019-06-25 14:36:44',
                ),
            30 =>
                array(
                    'id' => 38,
                    'name' => '创建文章',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/article/create',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 37,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 14:40:33',
                ),
            31 =>
                array(
                    'id' => 39,
                    'name' => '显示文章',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/article/show',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 37,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 14:41:10',
                ),
            32 =>
                array(
                    'id' => 40,
                    'name' => '保存文章',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/article/store',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 37,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 14:41:41',
                ),
            33 =>
                array(
                    'id' => 41,
                    'name' => '编辑文章',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/article/edit',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 37,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 14:42:02',
                ),
            34 =>
                array(
                    'id' => 42,
                    'name' => '修改文章',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/article/update',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 37,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 14:42:41',
                ),
            35 =>
                array(
                    'id' => 43,
                    'name' => '删除文章',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/article/destroy',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 37,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 14:43:31',
                ),
            36 =>
                array(
                    'id' => 44,
                    'name' => '上传图片',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/article/uploadImage',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 37,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 14:44:34',
                ),
            37 =>
                array(
                    'id' => 45,
                    'name' => '文章分类',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/category/index',
                    'level' => 1,
                    'icon' => 'layui-icon-list',
                    'parent_id' => 36,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 14:50:47',
                ),
            38 =>
                array(
                    'id' => 46,
                    'name' => '创建分类',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/category/create',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 45,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 14:51:45',
                ),
            39 =>
                array(
                    'id' => 47,
                    'name' => '保存分类',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/category/store',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 45,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 14:52:10',
                ),
            40 =>
                array(
                    'id' => 48,
                    'name' => '查看分类',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/category/show',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 45,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 14:52:42',
                ),
            41 =>
                array(
                    'id' => 49,
                    'name' => '编辑分类',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/category/edit',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 45,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 14:53:04',
                ),
            42 =>
                array(
                    'id' => 50,
                    'name' => '修改分类',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/category/update',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 45,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 14:53:24',
                ),
            43 =>
                array(
                    'id' => 51,
                    'name' => '删除分类',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/category/destroy',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 45,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 14:53:55',
                ),
            44 =>
                array(
                    'id' => 52,
                    'name' => '评论列表',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/comment/index',
                    'level' => 1,
                    'icon' => 'layui-icon-chat',
                    'parent_id' => 36,
                    'display_menu' => 1,
                    'created_at' => '2019-06-25 14:55:02',
                ),
            45 =>
                array(
                    'id' => 53,
                    'name' => '删除评论',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/comment/destroy',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 52,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 14:55:39',
                ),
            46 =>
                array(
                    'id' => 54,
                    'name' => '批量替换',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/comment/replace',
                    'level' => 2,
                    'icon' => 'layui-icon-survey',
                    'parent_id' => 52,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 14:57:40',
                ),
            47 =>
                array(
                    'id' => 55,
                    'name' => '有些话',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/chat/index',
                    'level' => 1,
                    'icon' => 'layui-icon-face-surprised',
                    'parent_id' => 36,
                    'display_menu' => 1,
                    'created_at' => '2019-06-25 15:04:23',
                ),
            48 =>
                array(
                    'id' => 56,
                    'name' => '查看有些话',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/chat/show',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 55,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 15:05:08',
                ),
            49 =>
                array(
                    'id' => 57,
                    'name' => '添加有些话',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/chat/create',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 55,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 15:05:52',
                ),
            50 =>
                array(
                    'id' => 58,
                    'name' => '保存有些话',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/chat/store',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 55,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 15:06:25',
                ),
            51 =>
                array(
                    'id' => 59,
                    'name' => '编辑有些话',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/chat/edit',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 55,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 15:07:10',
                ),
            52 =>
                array(
                    'id' => 60,
                    'name' => '修改有些话',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/chat/update',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 55,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 15:07:35',
                ),
            53 =>
                array(
                    'id' => 61,
                    'name' => '删除有些话',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/chat/destroy',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 55,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 15:08:01',
                ),
            54 =>
                array(
                    'id' => 62,
                    'name' => '标签管理',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/tag/index',
                    'level' => 1,
                    'icon' => 'layui-icon-note',
                    'parent_id' => 36,
                    'display_menu' => 1,
                    'created_at' => '2019-06-25 15:08:48',
                ),
            55 =>
                array(
                    'id' => 63,
                    'name' => '查看标签',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/tag/show',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 62,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 15:10:37',
                ),
            56 =>
                array(
                    'id' => 64,
                    'name' => '创建标签',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/tag/create',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 62,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 15:23:49',
                ),
            57 =>
                array(
                    'id' => 65,
                    'name' => '保存标签',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/tag/store',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 62,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 15:29:27',
                ),
            58 =>
                array(
                    'id' => 66,
                    'name' => '编辑标签',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/tag/edit',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 62,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 15:29:51',
                ),
            59 =>
                array(
                    'id' => 67,
                    'name' => '修改便签',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/tag/upda',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 62,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 15:30:29',
                ),
            60 =>
                array(
                    'id' => 68,
                    'name' => '删除标签',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/tag/destroy',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 62,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 15:31:12',
                ),
            61 =>
                array(
                    'id' => 69,
                    'name' => '前台菜单',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/nav/index',
                    'level' => 1,
                    'icon' => 'layui-icon-spread-left',
                    'parent_id' => 36,
                    'display_menu' => 1,
                    'created_at' => '2019-06-25 15:36:35',
                ),
            62 =>
                array(
                    'id' => 70,
                    'name' => '展示前台菜单',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/nav/show',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 69,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 15:37:09',
                ),
            63 =>
                array(
                    'id' => 71,
                    'name' => '创建前台菜单',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/nav/create',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 69,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 15:37:35',
                ),
            64 =>
                array(
                    'id' => 72,
                    'name' => '保存前台菜单',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/nav/store',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 69,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 15:38:05',
                ),
            65 =>
                array(
                    'id' => 73,
                    'name' => '编辑前台菜单',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/nav/edit',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 69,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 15:38:26',
                ),
            66 =>
                array(
                    'id' => 74,
                    'name' => '修改前台菜单',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/nav/update',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 69,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 15:38:49',
                ),
            67 =>
                array(
                    'id' => 75,
                    'name' => '删除前台菜单',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/nav/destroy',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 69,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 15:39:14',
                ),
            68 =>
                array(
                    'id' => 76,
                    'name' => '友情链接',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/friendLinks/index',
                    'level' => 1,
                    'icon' => 'layui-icon-link',
                    'parent_id' => 36,
                    'display_menu' => 1,
                    'created_at' => '2019-06-25 15:41:50',
                ),
            69 =>
                array(
                    'id' => 77,
                    'name' => '查看友情链接',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/friendLinks/show',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 76,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 15:42:16',
                ),
            70 =>
                array(
                    'id' => 78,
                    'name' => '添加友情链接',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/friendLinks/create',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 76,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 15:42:40',
                ),
            71 =>
                array(
                    'id' => 79,
                    'name' => '保存友情链接',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/friendLinks/store',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 76,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 15:43:03',
                ),
            72 =>
                array(
                    'id' => 80,
                    'name' => '编辑友情链接',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/friendLinks/edit',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 76,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 15:43:29',
                ),
            73 =>
                array(
                    'id' => 81,
                    'name' => '修改友情链接',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/friendLinks/update',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 76,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 15:44:26',
                ),
            74 =>
                array(
                    'id' => 82,
                    'name' => '删除友情链接',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/friendLinks/destroy',
                    'level' => 2,
                    'icon' => NULL,
                    'parent_id' => 76,
                    'display_menu' => 0,
                    'created_at' => '2019-06-25 15:44:50',
                ),
            75 =>
                array(
                    'id' => 83,
                    'name' => '用户列表',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/user/index',
                    'level' => 2,
                    'icon' => 'layui-icon-user',
                    'parent_id' => 6,
                    'display_menu' => 1,
                    'created_at' => '2019-07-27 07:21:48',
                ),
            76 =>
                array(
                    'id' => 84,
                    'name' => '查看用户',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/user/show',
                    'level' => 3,
                    'icon' => NULL,
                    'parent_id' => 83,
                    'display_menu' => 0,
                    'created_at' => '2019-07-27 07:22:58',
                ),
            77 =>
                array(
                    'id' => 85,
                    'name' => '创建用户',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/user/create',
                    'level' => 3,
                    'icon' => NULL,
                    'parent_id' => 83,
                    'display_menu' => 0,
                    'created_at' => '2019-07-27 07:24:14',
                ),
            78 =>
                array(
                    'id' => 86,
                    'name' => '保存用户',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/user/store',
                    'level' => 3,
                    'icon' => NULL,
                    'parent_id' => 83,
                    'display_menu' => 0,
                    'created_at' => '2019-07-27 07:25:07',
                ),
            79 =>
                array(
                    'id' => 87,
                    'name' => '编辑用户',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/user/edit',
                    'level' => 3,
                    'icon' => NULL,
                    'parent_id' => 83,
                    'display_menu' => 0,
                    'created_at' => '2019-07-27 07:26:00',
                ),
            80 =>
                array(
                    'id' => 88,
                    'name' => '更新用户',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/user/update',
                    'level' => 3,
                    'icon' => NULL,
                    'parent_id' => 83,
                    'display_menu' => 0,
                    'created_at' => '2019-07-27 07:27:31',
                ),
            81 =>
                array(
                    'id' => 89,
                    'name' => '删除用户',
                    'guard_name' => 'admin',
                    'sort_order' => 0,
                    'url' => '/admin/user/destroy',
                    'level' => 3,
                    'icon' => NULL,
                    'parent_id' => 83,
                    'display_menu' => 0,
                    'created_at' => '2019-07-27 07:28:07',
                ),
        );

        DB::table('permissions')->insert($data);
    }
}
